version: '3'
services:
  app:
    env_file: .env
    image: ${REGISTRY}/${REGISTRY_USER}/${REPO_NAME}:${TAG}
    build: 
      dockerfile: other.dockerfile
      context: .
      args:
        - BUILD_DATE=${BUILD_DATE}
        - REPO_NAME=${REPO_NAME}
        - DOCKER_IMAGE=${REGISTRY}/${REGISTRY_USER}/${REPO_NAME}:${TAG}
        - REGISTRY=${REGISTRY}
        - FILES=${FILES}
    ports:
      - "5000:5000"
    volumes:
      - /Users/humberto/Projects/app.share_portfolio:/home/app.share_portfolio

  jupyter:
    image: "jupyter/minimal-notebook:latest"
    ports:
      - "8888:8888"
    volumes:
      - /Users/humberto/Projects/app.share_portfolio:/home/jovyan/work
    
# volumes:
#     - $(echo pwd)